### ISSUE TITLE
Questions about formulas in code and papers

### ISSUE THREAD

**Issue by gzgz-code** [LTTM/SDR#12]
Hello, thank you for sharing your codes.
I have some questions about the paper and codes, I hope you can help me clear my doubts.
1. The first doubt is the Frobenius norm and MSELoss. Are Frobenius norm and MSE equal? Is the Frobenius norm in the paper reflected in the code with MSE?
2. Is the part of the green box in the image multiplied or the part of the vector in fi?
![image](https://user-images.githubusercontent.com/67822758/174926886-80feb455-75f1-4219-8e4b-ec03f67de7f0.png)
![image](https://user-images.githubusercontent.com/67822758/174926378-0a4d274d-5863-49b4-9e69-f1a597e48364.png)
Hope to get your answer, I will be very grateful.

**Comment by umbertomichieli** [comment]
Hi, thank you for your interest in our work. Below the answer to your doubts:

1) Yes, it is the same.

2) I'm not completely sure what you mean here. However, I notice there is a typo in Eq. (6) which I don't see in the CVF/Arxiv versions. Where did you find the version you are looking at? 
The correct formula does not have the vertical line after $c_j$, as you can see below ([link](https://arxiv.org/abs/2103.06342v3)).
The first part of the green boxes (e.g., $(f_i - p_c_j)$) is multiplied by the indicator function that follows. In other words, in Eq. (6) we are computing the distance between features $f_i$ and prototypes $p_c_j$ only when the feature $f_i$ belongs to class $c_j$ (this is what the second term does).
![Screenshot 2022-06-22 at 08 18 09](https://user-images.githubusercontent.com/24178865/174968325-7580c96e-7d67-46b3-ad5d-44ed65ff0347.png)

I hope your doubts are clarified.
