### ISSUE TITLE
The command about offline.

### ISSUE THREAD

**Issue by ljx97** [LTTM/SDR#3]
Hello, how to write the command when offline? Thank u.

**Comment by umbertomichieli** [comment]
Hi, you can run the offline setup via:

python -u -m torch.distributed.launch \
--nproc_per_node=1 run.py \
--batch_size 8 \
--logdir logs/offline/ \
--dataset voc \
--name offline \
--task offline \
--step 0 \
--lr 0.001 \
--epochs 30 \
--debug \
--sample_num 10 \
--where_to_sim GPU_windows

My apologies for the late reply.
I'm closing the issue for now, feel free to re-open it.

**Comment by ljx97** [comment]
Thank you very much!




On 09/20/2021 00:41, Umberto Michieli wrote:

Hi, you can run the offline setup via:

python -u -m torch.distributed.launch
--nproc_per_node=1 run.py
--batch_size 8
--logdir logs/offline/
--dataset voc
--name offline
--task offline
--step 0
--lr 0.001
--epochs 30
--debug
--sample_num 10
--where_to_sim GPU_windows

My apologies for the late reply.
I'm closing the issue for now, feel free to re-open it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
