### ISSUE TITLE
The split method in test data set

### ISSUE THREAD

**Issue by ljx97** [LTTM/SDR#4]
Hello, how is the test data set divided? For example, I observed that the content of /voc/19-1/test_on_val-1.npy is not exactly the same as the content of /voc/19-1/test_on_val-0.npy.
Why is the content of the test set different in each incremental step?

**Comment by umbertomichieli** [comment]
Hi, the test data set is divided in the standard way for incremental learning task: the test set at step k will contain only the images having classes which have already been learned by the model.
So test_on_val-0.npy is going to be a subset of test_on_val-1.npy (the images in the original test set which contain the tv/monitor class are not present in the test set of the step 0).

You can verify it by loading them and checking the lenghts of the arrays (i.e., the number of images).
te0 = np.load('test_on_val-0.npy')
te1 = np.load('test_on_val-1.npy')
len(te0)
len(te1)
len(np.setdiff1d(te1,te0))

I hope this answers your concerns.
Umberto

**Comment by ljx97** [comment]
Okey, thanks a lot.
