### ISSUE TITLE
Results for ADE20k and other Pascal VOC

### ISSUE THREAD

**Issue by hieuvmphan** [LTTM/SDR#5]
Hi, thanks for sharing your work.

I have a quick question. Could you please share the log results for ADE20k and other Pasacal VOC besides 19-1?

Thanks.

**Comment by umbertomichieli** [comment]
Hi, I apologize for the delayed answer. 
Attached you can find some [logs](https://github.com/LTTM/SDR/files/7662699/ade20k_results_share.zip) from the ade20k dataset. 
Regarding voc12: there are many scenarios, is there any specific one you are interested in?
I hope this can help you.
Note: the logs I'm sharing mught have been done with an older version of the code, thus they might be a bit different from the ones you see as output.

Kind Regards.
