### ISSUE TITLE
The command about 15-5s.

### ISSUE THREAD

**Issue by ljx97** [LTTM/SDR#8]
Hello,

Thank you for your interesting work. Recently I have been reproduction your work. But I failed. Would you please help me to check whether the running command is correct?

voc-15-5s

python run.py \
--batch_size 8 \
--logdir logs/15-5s/ \
--dataset voc \
--name FT \
--task 15-5s \
--step 0 \
--lr 0.001 \
--epochs 30 \
--debug \
--sample_num 10 \
--unce \
--loss_de_prototypes 1 \
--where_to_sim GPU_windows

python run.py \
--batch_size 8 \
--logdir logs/15-5s/ \
--dataset voc \
--name SDR1\
--task 15-5s \
--step 1 \
--lr 0.0001 \
--epochs 30 \
--debug \
--sample_num 10 \
--where_to_sim GPU_windows \
--method SDR \
--step_ckpt 'logs/15-5s/15-5s-voc_FT/15-5s-voc_FT_0.pth'

python run.py \
--batch_size 8 \
--logdir logs/15-5s/ \
--dataset voc \
--name SDR2
--task 15-5s \
--step 2 \
--lr 0.0001 \
--epochs 30 \
--debug \
--sample_num 10 \
--where_to_sim GPU_windows \
--method SDR \
--step_ckpt 'logs/15-5s/15-5s-voc_SDR1/15-5s-voc_SDR1_1.pth'

python run.py \
--batch_size 8 \
--logdir logs/15-5s/ \
--dataset voc \
--name SDR3
--task 15-5s \
--step 3 \
--lr 0.0001 \
--epochs 30 \
--debug \
--sample_num 10 \
--where_to_sim GPU_windows \
--method SDR \
--step_ckpt 'logs/15-5s/15-5s-voc_SDR2/15-5s-voc_SDR2_2.pth'

python run.py \
--batch_size 8 \
--logdir logs/15-5s/ \
--dataset voc \
--name SDR4
--task 15-5s \
--step 4 \
--lr 0.0001 \
--epochs 30 \
--debug \
--sample_num 10 \
--where_to_sim GPU_windows \
--method SDR \
--step_ckpt 'logs/15-5s/15-5s-voc_SDR3/15-5s-voc_SDR3_3.pth'

python run.py \
--batch_size 8 \
--logdir logs/15-5s/ \
--dataset voc \
--name SDR5
--task 15-5s \
--step 5 \
--lr 0.0001 \
--epochs 30 \
--debug \
--sample_num 10 \
--where_to_sim GPU_windows \
--method SDR \
--step_ckpt 'logs/15-5s/15-5s-voc_SDR4/15-5s-voc_SDR4_4.pth'

Thanks.

**Comment by umbertomichieli** [comment]
Hi, the commands look fine to me. However, I haven't tried them yet. I will get back to you once I am able to test them (hopefully in a week time)

**Comment by ljx97** [comment]
Thanks a lot. Looking forward to your reply.

**Comment by umbertomichieli** [comment]
Hi, as I said I don't have computing resources available at the present time to run your commands. 
Therefore, I would like you to run another experiment first of all, disabling the contrastive learning part.

First of all, please create a folder logs/15-5s/15-5s-voc_NEW_de_prototypes/ and place here this [file](https://drive.google.com/file/d/1wa67f_AjOPgYSIqPTpMFtD3MrX3tL7jT/view?usp=sharing) (it is the checkpoint of the step 0, containing also prototypes).

Then, you can run the attached sh file: [script_share_v2.sh.zip](https://github.com/LTTM/SDR/files/7666845/script_share_v2.sh.zip)

In a recent experiment using this configuration I achieved 46% of mIoU. Please, let me know if you can reach the same.
Note that to achieve the final results of the paper you would need to add the contrastive learning part on top of this.

I hope this could help you.
I will further debug the commands you sent me in a later stage.

**Comment by ljx97** [comment]
Thanks a lot. I have download the files you upload. I will try it. Thanks again.

**Comment by umbertomichieli** [comment]
I think I spot the issue in the provided code: it is about the proper loading of the old model. 
I think the commands you passed me actually load the model of FT in the subsequent steps (even though step_ckpt is provided). This is because I usually keep the same name (i.e., SDR) for a full simulation (i.e., I don't split it in SDR1, SDR2, SDR3,...)

You can start from the file I shared in my previous comment and you should get ~46% mIoU. 
Closing this for now, feel free to re-open it.
Kind Regards.

**Comment by ljx97** [comment]
Hello, I tried to run the code with the same name 'SDR' and confirm the correctness of loading old model through debug, but I still failed to get the results in the paper. Here's what I got:

parameter: voc 15-5s disjoint batch=8 epoch=30 
step 0 mIoU: 78.73
step 1 mIoU: 65.17
step 2 mIoU: 35.32
step 3 mIoU: 18.49
step 4 mIou: 16.22
step 5 mIoU: 14.95
